# Generated by Django 4.2.1 on 2023-05-29 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='категория предложения')),
            ],
            options={
                'verbose_name': 'Категория калькулятора',
                'verbose_name_plural': 'Категории калькулятора',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(db_index=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Город калькулятора',
                'verbose_name_plural': 'Города калькулятора',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_offer', models.CharField(max_length=200, verbose_name='Наименование предложения')),
                ('price', models.FloatField(max_length=20, verbose_name='Цена')),
                ('discount', models.FloatField(max_length=20, verbose_name='Скидка')),
                ('category_offer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='calculator_main.categoryoffer', verbose_name='категория предложения')),
            ],
            options={
                'verbose_name': 'Наименования предложения',
                'verbose_name_plural': 'Наименовании предложений',
            },
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='city_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='calculator_main.city', verbose_name='Город'),
        ),
    ]
