# Generated by Django 4.2.1 on 2023-05-30 12:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitiesTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='MailingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_type', models.CharField(max_length=30, verbose_name='Вид рассылки')),
            ],
        ),
        migrations.CreateModel(
            name='UrlsContentMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster_url', models.URLField(db_index=True, verbose_name='Ссылка на мероприятие')),
                ('text_content', models.TextField(verbose_name='Описание мероприятия')),
                ('event_category', models.CharField(max_length=20, verbose_name='Категория мероприятия')),
                ('name_event', models.CharField(max_length=30, verbose_name='Название мероприятия')),
                ('rate', models.CharField(max_length=3, verbose_name='Ценз')),
                ('date_event', models.CharField(max_length=10, verbose_name='Дата мероприятия')),
                ('time_event', models.CharField(max_length=10, verbose_name='Время мероприятия')),
                ('venue', models.CharField(max_length=30, verbose_name='Площадка')),
                ('price', models.CharField(max_length=15, verbose_name='Цена')),
                ('img_poster', models.ImageField(upload_to='main', verbose_name='Афиша')),
            ],
        ),
        migrations.CreateModel(
            name='UrlsContentTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_phone_links', models.CharField(max_length=30, verbose_name='Ссылка на телефон')),
                ('number_phone', models.CharField(max_length=30, verbose_name='Номер телефона')),
                ('alert_date', models.CharField(max_length=10, verbose_name='Дата переноса')),
                ('labels', models.CharField(max_length=300, verbose_name='UTM-метки')),
                ('pixels', models.CharField(max_length=300, verbose_name='Пиксель')),
                ('key', models.CharField(max_length=300, verbose_name='Ключ рассылки')),
                ('social', models.CharField(max_length=300, verbose_name='Соцсети')),
            ],
        ),
        migrations.CreateModel(
            name='ListAllUrls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create_mail', models.DateField(verbose_name='Дата рассылки')),
                ('city_mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_city', to='calculator_main.citiestemplate', verbose_name='Город')),
                ('type_mail', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_mail_type', to='calculator_main.mailingtype', verbose_name='Вид рассылки')),
                ('urls_content', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_urls_content', to='calculator_main.urlscontentmail', verbose_name='Ссылка на рассылку')),
                ('urls_transfer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_url_transfer', to='calculator_main.urlscontenttransfer', verbose_name='Содержимое для переноса')),
                ('user_create', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='list_user', to=settings.AUTH_USER_MODEL, verbose_name='Созатель рассылки')),
            ],
        ),
    ]
