# Generated by Django 4.2.1 on 2023-06-01 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculator_main', '0002_citiestemplate_mailingtype_urlscontentmail_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citiestemplate',
            options={'verbose_name': 'Город', 'verbose_name_plural': 'Города шаблонизатора'},
        ),
        migrations.AlterModelOptions(
            name='listallurls',
            options={'verbose_name': 'Ссылка на мероприятие', 'verbose_name_plural': 'Ссылки на мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='mailingtype',
            options={'verbose_name': 'Вид рассылки', 'verbose_name_plural': 'Виды рассылок'},
        ),
        migrations.AlterModelOptions(
            name='urlscontentmail',
            options={'verbose_name': 'Информация о мероприятии', 'verbose_name_plural': 'Мероприятия шаблонизатора'},
        ),
        migrations.AlterModelOptions(
            name='urlscontenttransfer',
            options={'verbose_name': 'Информация о переносе', 'verbose_name_plural': 'Данные для переноса'},
        ),
        migrations.AlterField(
            model_name='listallurls',
            name='urls_transfer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='list_url_transfer', to='calculator_main.urlscontenttransfer', verbose_name='Содержимое для переноса'),
        ),
        migrations.AlterField(
            model_name='urlscontentmail',
            name='img_poster',
            field=models.ImageField(upload_to='media/calculator_main/img', verbose_name='Афиша'),
        ),
    ]
